# Generated by Django 2.0.4 on 2018-04-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bombero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=8)),
                ('foto', models.ImageField(blank=True, upload_to='apps/servicios/static/profile_pictures/')),
                ('cargo', models.CharField(choices=[('Oficial de servicio', 'Oficial de servicio'), ('Piloto de maquina', 'Piloto de maquina'), ('Camillero', 'Camillero')], max_length=20)),
                ('activo', models.BooleanField()),
                ('registrado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
